#pragma once

#include <algorithm>
#include "bases.h"


namespace strategies {
/**
 * Strategy which generates ``std::vector`` instances
 * with sizes and elements generated from corresponding strategies.
 * @tparam Element: type of vectors elements generated by strategy.
 */
template<typename Element>
class Vectors : public CloneHelper<std::vector<Element>, Vectors<Element>> {
  using SizesStrategy = Strategy<size_t>;
  using ElementsStrategy = Strategy<Element>;
 public:
  /**
   * @param sizes: strategy to generate vectors sizes from.
   * @param elements: strategy to generate vectors elements from.
   */
  Vectors(std::shared_ptr<SizesStrategy> sizes,
          std::shared_ptr<ElementsStrategy> elements) :
      sizes_(std::move(sizes)),
      elements_(std::move(elements)) {};

  /**
   * Generates pseudo-random ``std::vector`` instance.
   */
  std::vector<Element> operator()() const override {
    size_t size = (*sizes_)();
    std::vector<Element> result(size);
    // FIXME: workaround using bind to get producer from strategy
    auto elements_producer = std::bind(&ElementsStrategy::operator(),
                                       elements_);
    std::generate_n(result.begin(),
                    size,
                    elements_producer);
    return result;
  }

 private:
  std::shared_ptr<SizesStrategy> sizes_;
  std::shared_ptr<ElementsStrategy> elements_;
};
}
