sudo: required

services:
  - docker

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

script:
  - ./run-tests.sh

after_success:
  - sudo ./update-coverage.sh

after_script:
  - ./cleanup.sh
