sudo: required

services:
  - docker

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

script:
  - ./run-tests.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      source update-coverage.sh
    fi

after_script:
  - ./cleanup.sh
