sudo: true

services:
  - docker

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - lcov

install:
  - ./install-docker.sh
  - ./install-docker-compose.sh

script:
  - ./run-tests.sh

after_success:
  - ./update-coverage.sh

after_script:
  - ./cleanup.sh
