sudo: false
dist: trusty

services:
  - docker

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - docker-ce
        - lcov

script:
  - ./run-tests.sh

after_success:
  - ./update-coverage.sh

after_script:
  - ./cleanup.sh
