version: '3'

services:
  cauldron:
    build:
      context: .
      args:
        CMAKE_VERSION: 3.9.5
        CATCH_VERSION: 2.0.1
    image: lycantropos/cauldron:0.0.0
    container_name: cauldron
    volumes:
      - ./cmake:/opt/cauldron/cmake
      - ./CMakeLists.txt:/opt/cauldron/CMakeLists.txt
      - ./cauldron:/opt/cauldron/cauldron
      - ./tests:/opt/cauldron/tests
      - ./run-plain-tests.sh:/opt/cauldron/run-plain-tests.sh
